version: '3.3'

services:

    squad:
      #image: cm2network/squad:latest
      image: reg.wizznet.co.uk:80/wizznet/squad-games-server-docker
      build:
        context: ./remotesquad
        dockerfile: buster/Dockerfile
      restart: always
      ports:
       - "7787:7787"
       - "7787:7787/udp"
       - "7788:7788"
       - "7788:7788/udp"
       - "21114:21114"
       - "21114:21114/udp"
       - "27165:27165"
       - "27165:27165/udp"
       - "27166:27166"
       - "27166:27166/udp"
      volumes:
       - ./squad-data:/home/steam/squad-dedicated
      networks:
        - wizznet
networks:
  wizznet:
